list_visits:
  fields:
    date:
      selector:
        date:
    days:
      default: 1
      selector:
        number:
          min: 1
          max: 7
          mode: box
    cat:
      selector:
        device:
          filter:
            integration: siipet
            model: Cat
